apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenapplication
  labels:
    app: mavenapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenapplication
  template:
    metadata:
      labels:
        app: mavenapplication
    spec:
      containers:
      - name: mavenapplication
        image: tomcat:9.0  # Using the official Tomcat image, modify if a custom image is required
        ports:
        - containerPort: 8080  # Tomcat's default port
        volumeMounts:
        - name: mavenapplication
          mountPath: /usr/local/tomcat/webapps  # Tomcat's default directory for WAR files
      volumes:
      - name: mavenapplication
        emptyDir: {}  # Placeholder, replace with PersistentVolume if required
