apiVersion: v1
kind: Service
metadata:
  name: mavenapplication
  labels:
    app: mavenapplication
spec:
  type: NodePort  # Use LoadBalancer if deploying on cloud infrastructure
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: mavenapplication
